### ISSUE TITLE
The first time i tried to self-host

### ISSUE THREAD

**Issue by AHIRAISSHY** [ClarityCafe/F.Lute#5]
2019-06-28T21:07:54.543883+00:00 app[worker.1]: Traceback (most recent call last):

2019-06-28T21:07:54.543908+00:00 app[worker.1]:   File "/app/main.py", line 8, in <module>

2019-06-28T21:07:54.543910+00:00 app[worker.1]:     cfg = Config.from_environment()

2019-06-28T21:07:54.543912+00:00 app[worker.1]:   File "/app/bot/structures/config.py", line 29, in from_environment

2019-06-28T21:07:54.543914+00:00 app[worker.1]:     channel_name=os.environ["FLUTE_CHANNEL_NAME"]

2019-06-28T21:07:54.543916+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/os.py", line 678, in __getitem__

2019-06-28T21:07:54.543918+00:00 app[worker.1]:     raise KeyError(key) from None

2019-06-28T21:07:54.543920+00:00 app[worker.1]: KeyError: 'FLUTE_CHANNEL_NAME'

**Comment by Martmists-GH** [comment]
You did not create a config.json file. Clearer instructions for self-hosting will soon come in README.md, for now do `cp config.json.example config.json && vi config.json` and enter the required information.

Leaving issue open to address reworking of README.

**Comment by sr229** [comment]
Hey there, sorry I did not document this properly. I will update the Heroku configuration shortly.

**Comment by sr229** [comment]
@KoalaBeans Hey there, I think I fixed the concern, please make another instance of F-Lute again, don't forget to delete the old one!
